---
title: "OS Focus Group: Data Prep"
---


# Packages
```{r}
library(tidyverse) # install.packages('tidyverse')
library(viridis)  # install.packages('viridis')
library(wordcloud) # install.packages('wordcloud')
library(tm) # install.packages('tm')
library(data.tree) # install.packages('data.tree')

```

# Load the Transcripts
Function for loading and cleaning the transcripts
```{r}
readTranscript <- function(file, transcriptName, commentRows) {
  transcript <- utils::read.delim(file,
                                   fileEncoding="UTF-8") %>%
  as.data.frame() %>%
  
  # Renaming the data to be Comments, and removing the empty lines
  dplyr::rename(Comment = 1) %>%
  dplyr::filter(Comment != "") %>%
  
  # Filtering just the comments, exluding the comments
  dplyr::filter(between(row_number(),commentRows[1],commentRows[2])) %>%
  
  # Creating a transcript column, generating the participant ID's from the columns, and prepping for when a comment was separated into two paragraphs
  dplyr::mutate(Transcript = transcriptName,
                Participant = gsub("\\:.*", "", Comment),
                altParticipant = lag(Participant,1),
                commentNumber = row_number(),
                altCommentNumber = lag(commentNumber,1)) %>%
  dplyr::relocate(Comment, .after = Participant) %>%
  
  # Merging when the comment went to a second line
  dplyr::mutate(Participant = ifelse(Participant == Comment,
                                     altParticipant,
                                     Participant),
                newLine = case_when(
                  .$Participant %in% .$Comment ~ "TRUE",
                  TRUE ~ "FALSE"
                ),
                commentNumber = ifelse(newLine == TRUE,
                                     altCommentNumber,
                                     commentNumber),
                commentNumber = case_when(
                  Transcript == "nonR1_2" & commentNumber == 58 ~ 59,
                  TRUE ~ commentNumber
                ),
                Participant = case_when(
                  Participant == "So yeah, I I did make myself a personal website, and it does take a lot of time and work, and" ~ "11",
                  TRUE ~ Participant
                )) %>%
  
  # Finding the comments that went onto new lines and merging them with the previous comment
    group_by(Transcript, Participant, commentNumber) %>% 
    mutate(Comment = paste0(Comment, collapse = " ")) %>%
    dplyr::ungroup() %>%
    dplyr::select(!c(altParticipant,altCommentNumber, newLine)) %>%
    dplyr::distinct(.keep_all = T) %>%
    
  # Remaking the comment numbers with the new distinct data
    dplyr::mutate(commentNumber = row_number()) %>%
  
  # Remove the square brackets that were inserted due to coding/comments
  dplyr::mutate(Comment = gsub("\\[[^][]*]", "", Comment),
                Participant = gsub("\\[[^][]*]", "", Participant))
  
  return(transcript)
}
```

Loading the transcripts
```{r}
# R1 1
transcript_R1_1 <- readTranscript(
  file = "Data/Raw Data/Transcripts/MASTER_R1_Transcript_2023_05_15.txt",
  transcriptName = "R1_1",
  commentRows = c(2,127)
)

# R1 2
transcript_R1_2 <- readTranscript(
  file = "Data/Raw Data/Transcripts/MASTER_R1_transcript_2023_05_22.txt",
  transcriptName = "R1_2",
  commentRows = c(2,134)
)

# nonR1 1
transcript_nonR1_1 <- readTranscript(
  file = "Data/Raw Data/Transcripts/MASTER CONSENSUS_NonR1_Transcript_2023_07_20.txt",
  transcriptName = "nonR1_1",
  commentRows = c(2,170)
)

# nonR1 2
transcript_nonR1_2 <- readTranscript(
  file = "Data/Raw Data/Transcripts/MASTER CONSENSUS_NonR1_Transcript_2023_05_15.txt",
  transcriptName = "nonR1_2",
  commentRows = c(2,112)
)

masterTranscript <- rbind(
  transcript_R1_1,
  transcript_R1_2,
  transcript_nonR1_1,
  transcript_nonR1_2)

rm(transcript_R1_1,
  transcript_R1_2,
  transcript_nonR1_1,
  transcript_nonR1_2)

# Export the codeReferences
utils::write.csv(
  x = masterTranscript,
  file = "Data/Prepped Data/masterTranscript.csv",
  fileEncoding = "UTF-8")
```

# Load the Codes & References
```{r}
codeReferences_nonR1_1 <- read.csv(
  file = "Data/Raw Data/Codes & References/CodeReferences_nonR1_1.csv",
  encoding="UTF-8") %>%
  dplyr::mutate(Transcript = "nonR1_1")

codeReferences_nonR1_2 <- read.csv(
  file = "Data/Raw Data/Codes & References/CodeReferences_nonR1_2.csv",
  encoding="UTF-8") %>%
  dplyr::mutate(Transcript = "nonR1_2")

codeReferences_R1_1 <- read.csv(
  file = "Data/Raw Data/Codes & References/CodeReferences_R1_1.csv",
  encoding="UTF-8") %>%
  dplyr::mutate(Transcript = "R1_1")

codeReferences_R1_2 <- read.csv(
  file = "Data/Raw Data/Codes & References/CodeReferences_R1_2.csv",
  encoding="UTF-8") %>%
  dplyr::mutate(Transcript = "R1_2")

codeReferences <- rbind(
  codeReferences_nonR1_1,
  codeReferences_nonR1_2,
  codeReferences_R1_1,
  codeReferences_R1_2
) %>%
  dplyr::relocate(Transcript, .before = Page) %>%
  dplyr::rename(Code = Comment,
                Comment = `Reference.Text`,
                Date = `Date...Time`) %>%
  
  # Filtering out non-code commments
  dplyr::filter(!grepl(pattern = "_Re-opened_", x = Code)) %>%
  dplyr::filter(!grepl(pattern = "_Marked as resolved_", x = Code)) %>%
  dplyr::filter(!grepl(pattern = "started coding first 3 responses for", x = Code)) %>%
  dplyr::filter(!grepl(pattern = "Note:", x = Code))

# Export the codeReferences
utils::write.csv(
  x = codeReferences,
  file = "Data/Prepped Data/codeReferences.csv",
  fileEncoding = "UTF-8")

rm(codeReferences_nonR1_1,
  codeReferences_nonR1_2,
  codeReferences_R1_1,
  codeReferences_R1_2
)
```

# Codebook Data
```{r}
cb_Initial <- read.csv(
  file = "Data/Raw Data/Codebook Data/Initial Codebook.csv",
  fileEncoding = "UTF-8"
) %>%
  dplyr::rename(initialCode = 2,
                codeName = 3,
                definition = 4) %>%
  dplyr::select(initialCode:definition) %>%
  dplyr::filter(initialCode != "")

cb_Axial <- read.csv(
  file = "Data/Raw Data/Codebook Data/Axial Codebook.csv",
  fileEncoding = "UTF-8"
) %>%
  dplyr::rename(axialCode = 2,
                initialCode = 3,
                codeName = 4,
                definition = 5) %>%
  dplyr::select(axialCode:definition) %>%
  dplyr::filter(initialCode != "")

cb_subcat <- read.csv(
  file = "Data/Raw Data/Codebook Data/Subcategory Codebook.csv",
  fileEncoding = "UTF-8"
) %>%
  dplyr::rename(axialCode = 3,
                codeName = 4,
                keywords = 5,
                definition = 6) %>%
  dplyr::select(1:axialCode) %>%
  dplyr::filter(axialCode != "")

# Creating the Master
cb_master <- base::merge(cb_Axial,cb_subcat, all = TRUE, no.dups = F) %>%
  dplyr::select(Subcategory, RQ, axialCode, initialCode, codeName, definition)
  
# Export the codeReferences
utils::write.csv(
  x = cb_master,
  file = "Data/Prepped Data/Master Codebook.csv",
  fileEncoding = "UTF-8")

rm(cb_Axial,
   cb_Initial,
   cb_subcat)
```

# Obtaining Frequency Counts
```{r}

codeReferences <- utils::read.csv(
  file = "Data/Prepped Data/codeReferences.csv",
  fileEncoding = "UTF-8") %>%
  dplyr::mutate(originalCode = Code) %>%
  tidyr::separate(Code, c("1", "2", "3", "4", "5", "6", "7"), ",") %>%
  tidyr::pivot_longer(cols = `1`:`7`,
                      values_to = "code") %>%
  dplyr::select(!name) %>%
  dplyr::filter(!is.na(code)) %>%
  dplyr::mutate(code = gsub(pattern = " ",
                            replacement = "",
                            code)) %>%
  dplyr::select(!X)

codeFreq <- codeReferences %>%
  dplyr::group_by(code) %>%
  dplyr::summarise(N = NROW(code),
                   Examples = paste0(Comment, collapse = " // ")) %>%
  dplyr::rename(initialCode = code)

cb_master <- utils::read.csv(
  file = "Data/Prepped Data/Master Codebook.csv",
  fileEncoding = "UTF-8") %>%
  base::merge(., codeFreq) %>%
  dplyr::relocate(initialCode, .after = axialCode) %>%
  dplyr::select(!X) %>%
  dplyr::mutate(freqWords = tm::tm_map(Examples, removePunctuation))

comments_clean <- VCorpus(VectorSource(cb_master$Examples)) %>%
  tm_map(removePunctuation) %>%
  tm_map(content_transformer(tolower)) %>%
  tm_map(removeNumbers) %>%
  tm_map(stripWhitespace) %>%
  tm_map(removeWords, stopwords('english')) %>% 
                  tidytext::unnest_tokens(output = word, input = Text) 

test <- data_frame(Text = cb_master$Examples) %>%
  tidytext::unnest_tokens(output = word, input = Text) %>%
                   anti_join(tidytext::stop_words) %>%
  count(word, sort = TRUE) %>%
  dplyr::filter(word != "yeah") %>%
  dplyr::mutate(word = case_when(
    word == "osf" ~ "OSF",
    word == "nih" ~ "NIH",
    TRUE ~ word
  ))

wordcloud(test$word, freq = test$n, scale = c(2,1), min.freq = 30,
          colors = colorRampPalette(brewer.pal(9,"Blues"))(32)[seq(8,32,6)])

ggsave(plot = last_plot())

utils::write.csv(
  x = cb_master,
  file = "Data/Prepped Data/Master Codebook_examples.csv",
  fileEncoding = "UTF-8")
```

# Trying to make a tree
```{r}
tree <- cb_master %>%
  dplyr::select(Subcategory, axialCode, initialCode) %>%
  dplyr::filter(Subcategory != "") %>%
  arrange(initialCode) %>%
  arrange(axialCode) %>%
  arrange(Subcategory)
d1 = tree %>%
  dplyr::select(Subcategory, axialCode) %>%
  dplyr::rename(from = 1,
                to = 2)
d2 = tree %>%
  dplyr::select(axialCode, initialCode) %>%
  dplyr::rename(from = 1,
                to = 2)

hierarchy <- rbind(d1, d2)

vertices <- data.frame(name = unique(c(as.character(hierarchy$from), as.character(hierarchy$to))) ) 

g <- igraph::graph_from_data_frame(hierarchy, vertices=NULL)

library(ggraph) # install.packages('ggraph')
treePlot <- ggraph(g,
                   layout='dendrogram',
                   circular=FALSE) + 
  geom_edge_link() + 
  geom_node_label(aes(label=names(V(g))),
                  size=2,
                  nudge_y=0) + 
  scale_y_reverse()  +
  coord_flip() +
  theme_classic()
treePlot

lay = layout.reingold.tilford(g) 
par(mar=c(0,0,0,0))
plot(g, layout=-lay[, 2:1],vertex.label.cex=0.7,
vertex.size=1,edge.arrow.size= 0.4)

ggsave(treePlot,
       filename = "Figures/TreePlot.png",
       height = 10,
       width = 6.5,
       units = "in",
       scale = 1)
```
```{r}
library(treemap)

```



```{r}
# Load data
data(USArrests)

# distance matrix 
dist_usarrests = dist(USArrests)

# hierarchical clustering analysis
clus_usarrests = hclust(dist_usarrests, method = "ward.D")

# Retreive data
class.dat <- classification(c("Pseudomonas putida", "Pseudomonas aeruginosa","Enterobacter xiangfangensis","Salmonella enterica","Klebsiella pneumoniae"), db = 'ncbi')

# Specify interest
interest <- c('superkingdom', 'phylum','class','order','genus','species')

# Convert to wide matrix
df2 <- bind_rows(class.dat, .id = "column_label") %>%
  dplyr::select(-id) %>% 
  filter(rank %in% interest) %>%
  spread(rank, name) %>%
  dplyr::select(-column_label) %>%
  dplyr::select(interest) %>% # we need the order
  as.matrix()

# Empty parent child matrix
parent.child <- matrix(nrow=0,ncol=2)

# Add data to parent child
for (i in 1:(ncol(df2)-1)){
  parent.child <- rbind(parent.child,df2[,c(i,i+1)])
}

# To dataframe and add colnmaes
parent.child <- as.data.frame(parent.child)
colnames(parent.child) <- c('from', 'to')

# Convert this to a ggraph
g <- graph_from_data_frame(parent.child)
ggraph(g,layout='dendrogram',circular=FALSE) + 
  geom_edge_link() + 
  geom_node_label(aes(label=names(V(g))),size=3,nudge_y=-0.1) + 
  scale_y_reverse(labels = interest)  + coord_flip() +
  theme_classic()
```


```{r}
```


```{r}
# Load data
data(USArrests)
# Compute distances and hierarchical clustering
dd <- dist(scale(USArrests), method = "euclidean")
hc <- hclust(dd, method = "ward.D2")
    
treeData <- cb_master %>%
  dplyr::select(Subcategory, axialCode, initialCode) %>%
  dplyr::filter(Subcategory != "") %>%
  arrange(Subcategory)

 df <- data.frame(x=c('A','A','B','B','B'), y=c('Ab','Ac','Ba', 'Ba','Bd'), z=c('Abb','Acc','Bad', 'Bae','Bdd'))
 test <- stree(df, level = 1)

#Tree
x <- maketreelist(treeData)

library(igraph) # install.packages('igraph')
g <- graph.data.frame(x)
plot(g)


level <- c(1, 2, 3, 4, 4, 3, 4, 4, 1, 2, 3)
value <- letters[1:11]

library(tidyverse)
library(data.tree)
library(networkD3) # install.packages('networkD3')

data.frame(level, value, stringsAsFactors = F) %>%
  mutate(row = row_number()) %>%
  mutate(level2 = level, value2 = value) %>%
  spread(level2, value2) %>%
  mutate(`0` = "") %>%
  arrange(row) %>%
  fill(-level, -value, -row) %>%
  gather(parent_level, parent, -level, -value, -row) %>%
  filter(parent_level == level - 1) %>%
  arrange(row) %>%
  select(parent, child = value) %>%
  data.tree::FromDataFrameNetwork() %>%
  data.tree::ToListExplicit(unname = TRUE) %>%
  networkD3::radialNetwork()
```



# Sample Descriptives
## Function
```{r}
practiceExp <- function(practice, codeData) {
  
practiceData <- codeData %>%
  dplyr::filter(grepl(
    pattern = practice,
    x = initialCodes)) %>%
  dplyr::mutate(
    Practice = practice,
    
    # Training Experience
    TE = case_when(
      grepl(paste0("TE-",Practice), initialCodes) ~ 1,
      TRUE ~ 0
    ),
    
    # Uncertainty
    U = case_when(
      grepl(paste0("U-",Practice), initialCodes) ~ 1,
      TRUE ~ 0
    ),
    
    # Lack of Previous Experience
    LPE = case_when(
      grepl(paste0("LPE-",Practice), initialCodes) ~ 1,
      TRUE ~ 0
    ),
    
    # Aware
    aware = case_when(
      grepl(paste0("A-",Practice), initialCodes) ~ 1,
      TRUE ~ 0
    ),
    
    # Knowledge of Procedures
    KOP = case_when(
      grepl(paste0("KOP-",Practice), initialCodes) ~ 1,
      TRUE ~ 0
    ),
    
    # Previous Experience
    PE = case_when(
      grepl(paste0("PE-",Practice), initialCodes) ~ 1,
      TRUE ~ 0
    ),
    
    # Want to Learn
    WTL = case_when(
      grepl(paste0("WTL-",Practice), initialCodes) ~ 1,
      TRUE ~ 0
    ),
    
    # Intend
    I = case_when(
      grepl(paste0("I-",Practice), initialCodes) ~ 1,
      TRUE ~ 0
    ),
  )

return(practiceData)
}
```

## Practices
```{r}
OER <-practiceExp(practice = "OER",
                  codeData = codes)
OD <- practiceExp(practice = "OD",
                  codeData = codes)
OA <- practiceExp(practice = "OA",
                  codeData = codes)
OM <-practiceExp(practice = "OM",
                  codeData = codes)
SA <-practiceExp(practice = "SA",
                  codeData = codes)
PR <-practiceExp(practice = "PR",
                  codeData = codes)
OS <-practiceExp(practice = "OS",
                  codeData = codes)
```
## Plots
### Experience
```{r}
experience <- rbind(
  OD, OA, OM, SA, PR, OS
) %>%
  dplyr::group_by(Group, Practice) %>%
  dplyr::summarise(
    #U = sum(U),
    LPE = sum(LPE),
    #aware = sum(aware),
    #KOP = sum(KOP),
    TE = sum(TE),
    PE = sum(PE),
    I = sum(I)
  ) %>%
  tidyr::pivot_longer(cols = LPE:I,
                      names_to = "ExpLvl",
                      values_to = "Count") %>%
  dplyr::mutate(Count = ifelse(ExpLvl == "LPE",Count*-1,Count),
                Count = ifelse(ExpLvl == "U",Count*-1,Count),
                ExpLvl = factor(ExpLvl,
                                levels = c(
                                  #"U",
                                  "LPE",
                                  #"aware",
                                  #"KOP",
                                  "I",
                                  "TE",
                                  "PE"),
                                labels = c(
                                  #"Uncertain about... (U)",
                                  "No Exp with... (LPE)",
                                   #"Aware of... (A)",
                                   #"Knowledge of... (KOP)",
                                  "Intends to use... (I)",
                                  "Received training with... (TE)",
                                  "Prior Exp with... (PE)")),
                Practice = factor(Practice,
                                  levels = c("OM",
                                             "OA",
                                             "PR",
                                             "OD",
                                             "SA",
                                             "OS")),
                Group = factor(Group,
                               levels = c("nonR1",
                                          "R1"),
                               labels = c("Non-R1",
                                          "R1")))

experience %>%
ggplot() +
  aes(fill = ExpLvl,
      y = Count,
      x = Practice,
      order = ExpLvl) + 
    geom_bar(
      position = "stack",
      stat = "identity") +
  theme_minimal() +
  facet_wrap(~ Group) +
  theme(panel.border = element_rect(color = "darkgrey",
                                    fill = NA),
        legend.position = "bottom") +
  # Colors
  scale_fill_viridis(discrete = TRUE,
                     direction = -1) +
  
  # Labels
  labs(
    fill = "Experience Level:",
    y = "Frequency Count",
    title = "Experience by OS Practice and Institutional Setting"
  )
  
ggsave(
  filename = "Figures/ExperiencePlot.png",
  height = 4,
  width = 6,
  units = "in",
  scale = 1.4,
  bg= "white"
)
```
### Knowledge
```{r}
knowledge <- rbind(
  OD, OA, OM, SA, PR, OS
) %>%
  dplyr::group_by(Group, Practice) %>%
  dplyr::summarise(
    U = sum(U),
    #LPE = sum(LPE),
    aware = sum(aware),
    KOP = sum(KOP),
    #TE = sum(TE),
    #PE = sum(PE),
    #I = sum(I)
  ) %>%
  tidyr::pivot_longer(cols = U:KOP,
                      names_to = "ExpLvl",
                      values_to = "Count") %>%
  dplyr::mutate(
                Count = ifelse(ExpLvl == "U",Count*-1,Count),
                ExpLvl = factor(ExpLvl,
                                levels = c(
                                  "U",
                                  #"LPE",
                                  "aware",
                                  "KOP"),
                                  #"I",
                                  #"TE",
                                  #"PE",

                                labels = c(
                                  "Uncertain about... (U)",
                                  #"No Exp with... (LPE)",
                                   "Aware of... (A)",
                                   "Knowledge of... (KOP)"),
                                  #"Intends to use... (I)",
                                  #"Received training with... (TE)",
                                  #"Prior Exp with... (PE)",
                                  ),
                Practice = factor(Practice,
                                  levels = c("OM",
                                             "OA",
                                             "PR",
                                             "OD",
                                             "SA",
                                             "OS")),
                Group = factor(Group,
                               levels = c("nonR1",
                                          "R1"),
                               labels = c("Non-R1",
                                          "R1")))

knowledge %>%
ggplot() +
  aes(fill = ExpLvl,
      y = Count,
      x = Practice,
      order = ExpLvl) + 
    geom_bar(
      position = "stack",
      stat = "identity") +
  theme_minimal() +
  facet_wrap(~ Group) +
  theme(panel.border = element_rect(color = "darkgrey",
                                    fill = NA),
        legend.position = "bottom") +
  # Colors
  scale_fill_viridis(discrete = TRUE,
                     direction = -1) +
  
  # Labels
  labs(
    fill = "Knowledge Level:",
    y = "Frequency Count",
    title = "Knowledge by OS Practice and Institutional Setting"
  )
  
ggsave(
  filename = "Figures/KnowledgePlot.png",
  height = 4,
  width = 6,
  units = "in",
  scale = 1.4,
  bg= "white"
)
```
# Codebook
```{r}

subcatCodebook <- rio::import("Data/Raw Data/Codebook Data/Subcategory Codebook.csv") %>%
  dplyr::rename(`Axial Code` = `Code abbreviation`) %>%
  dplyr::select(Subcategory:`Axial Code`)

masterCodebook <- rio::import("Data/Raw Data/Codebook Data/Austin's Master Codebook.csv") %>%
  dplyr::filter(`Axial Code` != "") %>%
  dplyr::select(!RQ) %>%
  base::merge(., subcatCodebook,
               all.x = T) %>%
  dplyr::relocate(Subcategory:RQ, .before = `Axial Code`) %>%
  dplyr::select(!c(V7:`Consensus?`))

rio::export(masterCodebook,
            file = "Data/Prepped Data/Master Codebook.csv")
```

# RQ1
```{r}

freqCount <- CodeCount %>%
  dplyr::rename(`Initial Code` = initialCodes)

masterCodebook <- rio::import(
            file = "Data/Prepped Data/Master Codebook.csv") %>%
  base::merge(., freqCount, all.y = T) %>%
  dplyr::filter(!is.na(RQ))

RQ <- masterCodebook %>%
  dplyr::filter(RQ != "N") %>%
  dplyr::mutate(match = ifelse(`Axial Code` == `Initial Code`,TRUE,FALSE)) %>%
  dplyr::filter(match == FALSE) %>%
    arrange(`Axial Code`)

library(ggalluvial) # install.packages("ggalluvial")

RQ %>%
  ggplot() +
  aes(
    #axis1 = Subcategory,
      axis1 = `Axial Code`,
      axis2 = `Initial Code`,
      y = Count,
      ) +
  scale_x_discrete(limits = c(
    #"Subcategory",
                              "Axial Code",
                              "Initial Code"),
                   expand = c(.2, .05)) +
  geom_alluvium(aes(fill = Group)) +
  geom_stratum() +
  geom_text(stat = "stratum", aes(label = after_stat(stratum))) +
  theme_minimal()

ggsave(plot = last_plot(),
       file = "Figures/RQ1.png",
       height = 8,
       width = 6,
       units = "in")

```

